pages/urls.py
from django.conf.urls import url
from pages.views import ReviewList, CreateReview

urlpatterns = [
    url(r'^review/create', CreateReview.as_view(), name='review_create'),
    url(r'^review/list', ReviewList.as_view(), name='review_list'),
]

vishleva/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.i18n import javascript_catalog
from photologue.views import PhotoDetailView

from pages.views import CreateReview, GalleryView, MainView, send_email

js_info_dict = {
    'domain': 'django',
    'packages': ('pages', 'vishleva'),
}

urlpatterns = [
    url(r'^jsi18n/$',
        javascript_catalog,
        js_info_dict,
        name='javascript-catalog'),
    url(r'^admin/', admin.site.urls),
    url(r'', include('two_factor.urls', 'two_factor')),
    url(r'^pages/', include('pages.urls', namespace='pages')),
    url(r'^$', MainView.as_view(), name='index'),
    url(r'^send_email$', send_email, name='send_email'),
    url(r'^jsi18n/$',
        javascript_catalog,
        js_info_dict,
        name='javascript-catalog'),
    url(r'^pages/', include('pages.urls', namespace="pages")),
    url(r'^mailing/', include('mailing.urls', namespace="mailing")),

    # photologue
    url(r'^photo/',
        include(
            [
                url(r'^gallery/(?P<slug>[\-\d\w]+)(?:/(?P<page>\d+))?/$',
                    GalleryView.as_view(),
                    name='pl-gallery'),
                url(r'^photo/(?P<slug>[\-\d\w]+)/$',
                    PhotoDetailView.as_view(),
                    name='pl-photo'),
            ],
            namespace='photologue')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

vishleva/models.py
from django.conf import settings
from django.db import models


class NullableEmailField(models.EmailField):
    """
        Subclass of the EmailField that
        allows empty strings to be stored as NULL.
    """

    description = "EmailField that stores NULL but returns ''."

    def from_db_value(self, value, expression, connection, contex):
        """
        Gets value right out of the db and changes it if its ``None``.
        """
        if value is None:
            return ''
        else:
            return value

    def to_python(self, value):
        """
        Gets value right out of the db or an instance, and changes it if its ``None``.
        """
        if isinstance(value, models.EmailField):
            return value
        if value is None:
            return ''
        return value

    def get_prep_value(self, value):
        """
        Catches value right before sending to db.
        """
        if value is '':
            # If Django tries to save an empty string, send the db None (NULL).
            return None
        else:
            # Otherwise, just pass the value.
            return value


class CommonInfo(models.Model):
    """ CommonInfo abstract model """

    AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')

    created_at = models.DateTimeField(
        auto_now_add=True, null=True, blank=True, editable=False)
    modified_at = models.DateTimeField(
        auto_now=True, null=True, blank=True, editable=False)
    created_by = models.ForeignKey(
        AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        editable=False,
        related_name="%(app_label)s_%(class)s_created_by")
    modified_by = models.ForeignKey(
        AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        editable=False,
        related_name="%(app_label)s_%(class)s_modified_by")

    def __str__(self):
        return getattr(self, 'name', '{} #{}'.format(
            type(self).__name__, str(self.id)))

    class Meta:
        abstract = True


class CommentMixin(models.Model):
    comment = models.TextField(null=True, blank=True, db_index=True)

    class Meta:
        abstract = True

vishleva/views.py
from django.http import JsonResponse


class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)
        else:
            return response

vishleva/templates/photologue/gallery_detail.html
{% extends "photologue/root.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{{ block.super }}. {{ gallery.title }}{% endblock %}

{% block content %}

    <div id="gallery-description" class="effect-oscar wowload fadeInLeft">
        <strong>{{ gallery.title|safe }}</strong><br><br>
        <small>{{ gallery.description|safe }}</small>
    </div>

    <div class="text-center">
    {% if photos.paginator.num_pages > 1 %}
            <ul class="pagination">
                {% for i in photos.paginator.page_range %}
                    <li {% if photos.number == i %}class="active"{% endif %}><a
                            href="{% url 'photologue:pl-gallery' slug=gallery.slug page=i %}">{{ i }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div id="gallery" class="wowload fadeIn text-center">
        <ul id="gallery-photos">
            {% for photo in photos %}
                <li>
                    <a href="{{ photo.get_display_url }}" title="{{ photo.title }}">
                        <img height="{{ photo.get_thumbnail_size.1 }}" width="{{ photo.get_thumbnail_size.0 }}"
                             src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}">
                    </a>
                </li>
            {% endfor %}
        </ul>

        {% if photos.paginator.num_pages > 1 %}
            <ul class="pagination">
                {% for i in photos.paginator.page_range %}
                    <li {% if photos.number == i %}class="active"{% endif %}><a
                            href="{% url 'photologue:pl-gallery' slug=gallery.slug page=i %}">{{ i }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
        <div class="slides"></div>
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
    </div>
{% endblock %}

vishleva/templates/photologue/root.html
{% extends "layout.html" %}