pages/urls.py
from django.conf.urls import url
from pages.views import ReviewList, CreateReview

urlpatterns = [
    url(r'^review/create', CreateReview.as_view(), name='review_create'),
    url(r'^review/list', ReviewList.as_view(), name='review_list'),
]

vishleva/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.i18n import javascript_catalog
from photologue.views import PhotoDetailView

from pages.views import CreateReview, GalleryView, MainView, send_email

js_info_dict = {
    'domain': 'django',
    'packages': ('pages', 'vishleva'),
}

urlpatterns = [
    url(r'^jsi18n/$',
        javascript_catalog,
        js_info_dict,
        name='javascript-catalog'),
    url(r'^admin/', admin.site.urls),
    url(r'', include('two_factor.urls', 'two_factor')),
    url(r'^pages/', include('pages.urls', namespace='pages')),
    url(r'^$', MainView.as_view(), name='index'),
    url(r'^send_email$', send_email, name='send_email'),
    url(r'^jsi18n/$',
        javascript_catalog,
        js_info_dict,
        name='javascript-catalog'),
    url(r'^pages/', include('pages.urls', namespace="pages")),
    url(r'^mailing/', include('mailing.urls', namespace="mailing")),

    # photologue
    url(r'^photo/',
        include(
            [
                url(r'^gallery/(?P<slug>[\-\d\w]+)(?:/(?P<page>\d+))?/$',
                    GalleryView.as_view(),
                    name='pl-gallery'),
                url(r'^photo/(?P<slug>[\-\d\w]+)/$',
                    PhotoDetailView.as_view(),
                    name='pl-photo'),
            ],
            namespace='photologue')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

pages/templates/pages/contacts.html
<div id="contact" class="spacer">
    <div class="container contactform center">
        <h2 class="text-center  wowload fadeInUp">
            Заказать фотографа<br>
            <small>
                <small><i class="fa fa-map-marker" aria-hidden="true"></i> Россия, Москва и Подмосковье</small>
            </small>
            <br>
            <small><a href="tel:+79037356096"><i class="fa fa-mobile"></i> +7 (903) 735-60-96</a></small>
            <br>
            <small><a href="mailto:mail@vishleva.com"><i class="fa fa-envelope-o"></i> mail@vishleva.com</a></small>
        </h2>
        <div class="row wowload fadeInLeftBig">
            <div class="col-sm-6 col-sm-offset-3 col-xs-12">
                <form action="{% url 'send_email' %}" method="post" id="contact-form">
                    {% csrf_token %}
                    {{ form.name }}
                    {{ form.contacts }}
                    {{ form.message }}
                    <button class="btn btn-primary" id="contact-form-button">
                        <i class="fa fa-paper-plane" id="contact-form-button-icon"></i> Отправить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

pages/templates/pages/galleries.html
{% load staticfiles %}

{% if galleries_even %}
<style>
    .grid figure {
        width: 50%;
    }
    @media screen and (max-width: 50em) {
        .grid figure {
        	width: 50%;
        }
    }
    @media (max-width: 639px) {
        .grid figure {width: 100%;}
    }
</style>
{% endif %}

<div id="works" class="clearfix grid">
    {% for gallery in galleries %}
        {% with photo=gallery.photos.all|first %}
            <figure class="effect-oscar  wowload fadeIn">
                {% if gallery.extended.is_special %}
                    <div class="works-special-banner">% скидка</div>
                {% endif %}
                <img src="{{ photo.get_thumbnail_gallery_url }}" alt="{{ photo.title }}">
                <figcaption>
                    <h2><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></h2>
                    <p>
                        <a class="no-border" href="{{ gallery.get_absolute_url }}">
                        {% if gallery.extended.small_description %}
                            {{ gallery.extended.small_description|safe }}
                        {% else %}{{ gallery.description|safe }}
                        {% endif %}
                        </a><br>
                        <a class="hidden-xs" href="{{ gallery.get_absolute_url }}">Посмотреть</a></p>
                </figcaption>
            </figure>
        {% endwith %}
    {% endfor %}
</div>

pages/templates/pages/index.html
{% extends  'layout.html' %}

{% load staticfiles %}
{% load i18n %}

{% block extrahead %}
    {{ extrahead.content|safe }}
{% endblock %}

{% block content %}
    {% include 'pages/galleries.html' %}

    {% for special in specials %}
        <div class="special {{ special.keywords }}">
            {{ special.content|safe }}
        </div>
    {% endfor %}

    <div id="about" class="container spacer about">
        {{ about.content|safe }}
    </div>


    <div class="highlight-info">
        <div class="overlay spacer">
            <div class="container">
                <div class="row text-center  wowload fadeInDownBig">
                    <div class="col-sm-3 col-xs-6">
                        <i class="fa fa-smile-o fa-5x"></i>
                        <h4>{% blocktrans count counter=clients %}{{ clients }} {{ name }}{% plural %}{{ clients }} {{ name }}{% endblocktrans %}</h4>
                    </div>
                    <div class="col-sm-3 col-xs-6">
                        <i class="fa fa-cart-arrow-down fa-5x"></i>
                        <h4>{% blocktrans count counter=orders %}{{ orders }} {{ name }}{% plural %}{{ orders }} {{ name }}{% endblocktrans %}</h4>
                    </div>
                    <div class="col-sm-3 col-xs-6">
                        <i class="fa fa-camera  fa-5x"></i>
                        <h4>{% blocktrans count counter=photos %}{{ photos }} {{ name }}{% plural %}{{ photos }} {{ name }}{% endblocktrans %}</h4>
                    </div>
                    <div class="col-sm-3 col-xs-6">
                        <i class="fa fa-calendar-o fa-5x"></i>
                        <h4>{% blocktrans count counter=days %}{{ days }} {{ name }}{% plural %}{{ days }} {{ name }}{% endblocktrans %}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'pages/reviews.html' %}


    <div id="prices" class="container spacer">
        {{ prices.content|safe }}
    </div>

    {% include 'pages/contacts.html' %}

{% endblock %}

pages/templates/pages/review_form.html
<form action="{% url 'pages:review_create' %}" method="post" id="review-form" class="contactform">
    {% csrf_token %}
    {{ form.text }}
    {{ form.contacts }}
    <input type="submit" class="hidden"/>
</form>

pages/templates/pages/review_list.html
{% extends "layout.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{{ block.super }}. {{ gallery.title }}{% endblock %}

{% block content %}

    <div id="content-description" class="wowload fadeInLeft">
        <strong>Отзывы</strong>, <small>оставленные моими клиентами</small>
        <div class="pull-right text-center">
                <button class="btn btn-success btn-sm" id="review-add-button" data-toggle="modal"
                        data-target="#review-form-modal">
                    <i class="fa fa-comment-o " id="review-add-button-icon"></i> Написать отзыв
                </button>
            </div>
    </div>

    <div id="content-body" class="wowload fadeIn">
        {% if is_paginated %}
            <div class="text-center">
                <ul class="pagination">
                    {% for i in paginator.page_range %}
                        <li {% if page_obj.number == i %}class="active"{% endif %}>
                            <a href="{% url 'pages:review_list' %}?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <div id="review-list-container" class="container">
        {% for review in object_list %}
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 review-list-item {% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}">
                     {% with gallery=review.photo.galleries.all|first %}
                        {% if review.photo %}
                            {% if gallery %}
                                <a href="{{ gallery.get_absolute_url }}" title="{{ gallery.title }}">
                            {% endif %}
                        <img class="img-responsive pull-left hidden-xs" src="{{ review.photo.get_thumbnail_url }}" alt="{{ review.photo.title }}">
                        {% if gallery %}</a>{% endif %}
                        {% endif %}
                    {% endwith %}
                    {{ review.text|safe }}
                    <div><strong>{{ review.client }}</strong></div>
                </div>
            </div>
        {% endfor %}
        </div>

        {% if is_paginated %}
            <div class="text-center">
                <ul class="pagination">
                    {% for i in paginator.page_range %}
                        <li {% if page_obj.number == i %}class="active"{% endif %}>
                            <a href="{% url 'pages:review_list' %}?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>

    {% include 'pages/review_modal.html' %}

{% endblock %}

pages/templates/pages/review_modal.html
{% load i18n %}
<div class="modal fade" id="review-form-modal" tabindex="-1" role="dialog" aria-labelledby="review-form-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Написать отзыв</h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" id="review-form-send"
                        data-close-text=" {% trans "close" %}">
                    {% trans "send" %}
                </button>
            </div>
        </div>
    </div>
</div>

pages/templates/pages/reviews.html
{% load i18n %}

<div id="reviews" class="container spacer">
    <h2 class="text-center  wowload fadeInUp">Отзывы моих довольных клиентов</h2>
    <div class="clearfix"></div>


    <div id="carousel-testimonials" class="carousel slide testimonails  wowload fadeInRight"
         data-ride="carousel">

        <div class="carousel-inner">
            {% for review in reviews %}
                <div class="item {{ forloop.counter0|yesno:",active" }} animated bounceInRight row">
                    <div class="animated slideInLeft col-sm-2 hidden-xs">
                        {% with gallery=review.photo.galleries.all|first %}
                            {% if review.photo %}
                                {% if gallery %}
                                    <a href="{{ gallery.get_absolute_url }}" title="{{ gallery.title }}">
                                {% endif %}
                            <img src="{{ review.photo.get_thumbnail_url }}" alt="{{ review.photo.title }}"
                                 class="img-responsive">
                            {% if gallery %}</a>{% endif %}
                            {% endif %}
                        {% endwith %}
                    </div>
                    <div class="col-sm-10">
                        {{ review.text|safe }}
                        <div><strong>{{ review.client }}</strong></div>
                    </div>
                </div>
            {% endfor %}

            <!-- Indicators -->
            <div></div>
            <ol class="carousel-indicators">
                {% for review in reviews %}
                    <li data-target="#carousel-testimonials" data-slide-to="{{ forloop.counter0 }}"
                        class="{{ forloop.counter0|yesno:",active" }}"></li>
                {% endfor %}
            </ol>
            <!-- Indicators -->
        </div>

        <div class="pull-right text-center">
            <a href="{% url 'pages:review_list' %}" class="btn btn-primary btn-sm" id="review-view-all">
                <i class="fa fa-bars" id="review-add-button-icon"></i> Все отзывы
            </a>

            <button class="btn btn-success btn-sm" id="review-add-button" data-toggle="modal"
                    data-target="#review-form-modal">
                <i class="fa fa-comment-o " id="review-add-button-icon"></i> Написать отзыв
            </button>
        </div>

    </div>
</div>

{% include 'pages/review_modal.html' %}